### ISSUE TITLE
Karma Test Explorer settings don't exist/show

### ISSUE THREAD

**Issue by mauriciogracia** [lucono/karma-test-explorer#15]
**Describe the Bug**

- After installing karma-test-explorer I dont see any of the pluging settings, especially the ones mentioned in the [Quick Start](https://github.com/lucono/karma-test-explorer#quick-start)

**Steps to Reproduce the Behavior**

(see screenshot below)

**Describe the Expected Behavior**

I expected to be able to set/change the settings `karmaTestExplorer.projectRootPath` and `karmaTestExplorer.karmaConfFilePath`

**Screenshots**

![imagen](https://user-images.githubusercontent.com/2321661/141320083-53d62aea-6331-46c0-97d3-f58a78164011.png)

**Please Provide the Following Information**
  - Extension version [0.3.0] - Nov 6, 2021
  - Windows 10 - 64 bits 
 - VScode version

Version: 1.62.1 (system setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by lucono** [comment]
@mauriciogracia This might be an issue with VS Code. Take a look at [this](https://github.com/microsoft/vscode/issues/104442) previous similar issue in the vscode project which might have some info on how to resolve this.

**Comment by lucono** [comment]
@mauriciogracia please reopen if this is still an issue
