### ISSUE TITLE
[Autorun]: Symbol of passed test case not green

### ISSUE THREAD

**Issue by LuigiDC** [lucono/karma-test-explorer#22]
I have a project that is based on Angular.After using the "Angular/Karma Test Explorer" before . I have found something that I am not sure if it should be a bug or a feature.

As approach of my test cases I use TDD. 
At the first execution of the test cases all are marked with a green or red tick. (OK so far)

Now I want to extend some of the code and specifically execute some of the test cases. For this I use the Autorun function. (OK as far as it goes)

As soon as a code change is detected, the selected test cases run again. Here I notice that after a short flash of the executed test cases none of the test results are displayed. The icon is grayed out again. Only a fail of the test result is displayed consistently.

My expectation would be that the results are always displayed with the current test run result. So always red or green but not gray for an executed test cases.

_The behavior only occurs when the autorun function runs the test cases. When I manually start the test, I always get a red or green test result._

**Debug Logs**
```
[2022-01-28 07:25:32.755] [DEBUG] [DefaultTestBuilder]: Processed 131 specs to build tests
[2022-01-28 07:25:32.757] [DEBUG] [TestSuiteOrganizer]: Rearranged 11 test files into folders
[2022-01-28 07:25:32.759] [DEBUG] [TestDiscoveryProcessor]: Test discovery - 131 total tests discovered from Karma
[2022-01-28 07:25:32.763] [DEBUG] [DefaultTestManager]: Discovered 131 total tests
[2022-01-28 07:25:32.763] [DEBUG] [Adapter]: Test discovery got 131 tests
[2022-01-28 07:25:32.763] [DEBUG] [Adapter]: Updating loaded test store
[2022-01-28 07:25:32.763] [DEBUG] [Adapter]: Storing newly loaded root suite
[2022-01-28 07:25:32.764] [DEBUG] [TestStore]: Clearing stored tests
[2022-01-28 07:25:32.764] [DEBUG] [TestStore]: Updating stored tests
[2022-01-28 07:25:32.780] [DEBUG] [Adapter]: Cannot run new test - Another test operation is still running
[2022-01-28 07:25:32.780] [DEBUG] [Notifications]: Showing 'Warning' notification with actions  and message: Cannot run new test - Another test operation is still running
[2022-01-28 07:25:32.781] [INFO] [Adapter]: Finished loading tests in 33.56 secs (131 tests loaded)
[2022-01-28 07:25:32.783] [DEBUG] [KarmaHttpTestRunExecutor]: Karma http request closed
```

**System Info**
 
 - OS: Windows 10
 - Node Version: v14.15.0
 - VSCode Version: 1.63.2
 - Karma Version: 6.3.12
 - Frameworks: Angular

**Picture of executed and passed test case**

![Executed_passed_testcase](https://user-images.githubusercontent.com/7841854/151505900-aab0e385-9830-4b83-83cf-4ec827141924.JPG)

**Comment by lucono** [comment]
Karma Test Explorer's watch implementation relies entirely on that of Karma, simply exposing the functionality in the extension's visual testing experience. So I suspect what you might be experiencing is the side effect of Karma's watch behavior which involves watching all tests, but only re-running the set of tests that were last run manually. Basically, Karma scopes its test watching to only re-run the set of tests in the last manually executed test run (ie. not executed by the watch functionality).

How that translates into Karma Test Explorer is that the last test run you performed manually (eg, by hitting the Run button on a test or test suite) then scopes subsequent test watching to only update those set of tests, while all other tests will not be updated to reflect changes. The set of tests being updated by auto-watch then changes again when another set of tests are subsequently executed in a new test run. (This watch behavior is definitely confusing inside of Karma Test Explorer).

To confirm if this is indeed the scenario you're running into, try manually running a single test, and then editing it to fail and pass, back and forth, and each time, check to see if its status is visually updated by auto-watch in Karma Test Explorer to the expected pass/fail state. You can also run ALL your tests in a  single test run by running the top-level suite, and (without manually running any more tests) then editing any of them back and forth to see if the status is visually updated automatically by the auto-watch feature.

**Comment by LuigiDC** [comment]
Hi. I think we're talking at cross purposes. It is not about the individual test case that I changed during the auto-watch. It's more about the ones that were already passed before and no longer undergo any changes. These statuses are not subsequently set to green in the auto-watch, although they are also tested and are green.

When executed manually, all statuses are always displayed.
In auto-watch mode, only the failed ones are marked.

1.First execution (manually to see visual results)
![grafik](https://user-images.githubusercontent.com/7841854/151717733-f34ba7b5-be00-4f23-971e-fa64ec409be5.png)

2. Change second test case to fail (auto-watch is active)
![grafik](https://user-images.githubusercontent.com/7841854/151717763-4d50c8ab-6a59-467e-82ba-7b5fe24eaf78.png)

The passed one is not green anymore only the failed one got correctly visualized.

3. Change test case back to passed.
![grafik](https://user-images.githubusercontent.com/7841854/151717800-b46eabee-9b8a-4641-beff-77ebee245c17.png)

No passed result visible.
With the old plugin, the results (passed & failed) of the executed test cases was always displayed, whether auto-watch or manually.

**Comment by lucono** [comment]
@LuigiDC What I'm referring to is Karma Test Explorer's `karmaTestExplorer.autoWatchEnabled` setting (enabled by default), which is the equivalent of Karma's watch feature. From your new screenshots, I see you're referring to the different (but similar) Autorun feature which can be activated from the Test Explorer UI.

If you simply disable Autorun from the UI, does the automatic test status update work better / more like you'd expect? Providing the `Karma Server` logs from the Output tab after testing that out, would also be very helpful.

**Comment by LuigiDC** [comment]
@lucono Ok. After deactivating the Autorun function from the UI, the changes were nevertheless detected and executed again. However, a passed is never 'freezed' as a result.

What I can see is that the test cases are all executed and briefly marked as passed (~300ms-500ms) and then only the failed status remains. I have attached you the requested Karma server log. There is a change from passed / fail / passed.
[Karma_Server_Log.txt](https://github.com/lucono/karma-test-explorer/files/7976779/Karma_Server_Log.txt)

Here you can see how the states just changes at the end.
![Animation](https://user-images.githubusercontent.com/7841854/151934472-3923c965-b422-4d04-a3c7-8dee85fce830.gif)

**Comment by lucono** [comment]
Ok, this seems like a bug. Do you have the `testExplorer.onReload` setting specified for your workspace? If so, what value do you have it set to?

**Comment by LuigiDC** [comment]
The user settings have been configured to `null `and for the workspace it was set to `reset`.
I also tried every combination out here, without any success or difference.

I configured now everything to `reset`.

Edit:
Ok i found out a solution which is working now.
I changed my settings as follow:

**From**
```
{
    "testExplorer.onReload": "reset",
    "testExplorer.onStart": "reset",
    "testExplorer.showExpandButton": 6,
    "testExplorer.sort": "byLocationWithSuitesFirst",
    "testExplorer.mergeSuites": true
}
```

**To**

```
{
    "testExplorer.showExpandButton": 6,
    "testExplorer.sort": "byLocationWithSuitesFirst",
    "testExplorer.mergeSuites": true,
}
```

I removed the onReload and onStart settings at all to achieve the result.
At the end the passed results are now faded out but still visible and fails are normal colorized.

**Comment by lucono** [comment]
Thanks for confirming. The passed tests shouldn't be faded - that's a bug, and can be fixed in the next release.

**Comment by lucono** [comment]
@LuigiDC I've made a tweak on the `beta` branch to address this. Test it out to confirm if it improves the issue. You can download the `.vsix` [artifact](https://github.com/lucono/karma-test-explorer/suites/5644320471/artifacts/184485538) from the CI build of the `beta` branch, or build it directly yourself from the branch.

**Comment by LuigiDC** [comment]
I installed the actifact. Fix seems to be ok.
Visualisation is now correct for failed test cases.

Thanks a lot.
