### ISSUE TITLE
multiple angular projects

### ISSUE THREAD

**Issue by jason53** [lucono/karma-test-explorer#27]
we work in a mono repo (https://blog.nrwl.io/angular/home) so we have multiple angular projects.  how do we switch between projects in this extension?  i know there is an extension setting for the "Default Angular Project Name" but is there a more dynamic way to switch between projects?

**Comment by lucono** [comment]
Are you looking to switch between the Angular projects in the Angular workspace (`angular.json`) that you currently have open in VSCode, or looking to switch between any random, completely unrelated, Angular project in your monorepo? The questions in the [feature request template](https://github.com/lucono/karma-test-explorer/issues/new?assignees=&labels=enhancement&template=feature_request.md) would be useful to capture how you envision the desired functionality.

**Comment by jason53** [comment]
I am looking to switch between Angular projects in the Angular workspace.  I see that this project was based off https://github.com/Raagh/angular-karma_test-explorer which is the extension I was using before this one.  That extension had a folder icon next to the refresh icon in the "Testing" panel that allowed you to click the project you wanted.

**Comment by lucono** [comment]
@jason53 I've added support for this to the `beta` branch. Download and try out the [vsix](https://github.com/lucono/karma-test-explorer/suites/5725698618/artifacts/189367494) to confirm if it works as expected.

**Comment by jason53** [comment]
> 

I installed the build and I now see that I am running version "v0.5.1" of the extension.  Is that correct?  Just asking b/c I have never manually installed an extension before so not sure if it worked.  So how do I switch between Angular projects?  I don't see a folder icon in the "Testing" panel.  Is there some other way?

**Comment by lucono** [comment]
Yes, v0.5.1 is the right version. The functionality should add a `+` button next to the refresh button, which can be used for loading other projects. The button will be available only if it is a multi-project Angular workspace open in VSCode.

**Comment by jason53** [comment]
> 

Ok.  I see the plus sign now (and the minus sign).  I had the default Angular project set in the extension settings so once I cleared that and restarted VSCode the plus sign showed up.  This is working as expected and I like that you allow more than one Angular project to be in the panel.  Thank you!  This extension is working great.

**Comment by jason53** [comment]
@lucono i wanted to follow-up on some behavior i am seeing with this version.  when i first start VSCode the default Angular project is loaded.  i can then set breakpoints and debug my tests and successfully hit the breakpoints i set.  next i click the "+" button and add another Angular projects to the test panel.  if i set breakpoints in the Angular project that was just added and debug the tests the breakpoints are never hit.  it behaves like i clicked the run button and not debug.  additionally, if i remove the first Angular project from the test panel and try and debug the tests from the second project i get an error saying a timeout occurred when trying to run the test.

**Comment by lucono** [comment]
@jason53 Can you attach environment information (same ones in the [bug template](https://github.com/lucono/karma-test-explorer/issues/new?template=bug_report.md)) and debug logs for both projects - that would help identify the issue.

**Comment by lucono** [comment]
Released in [v0.6.0](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#060---apr-6-2022)
