### ISSUE TITLE
Not able to run new test cases

### ISSUE THREAD

**Issue by shruthy-y** [lucono/karma-test-explorer#28]
**An alert shows up "Cannot run new test - Another test operation is still running", for indefinite time**

**Comment by lucono** [comment]
@shruthy-y Use the [bug template](https://github.com/lucono/karma-test-explorer/issues/new?template=bug_report.md) to provide environment and other information about the issue.

**Comment by lucono** [comment]
Closing due to no response. Please open a new issue if you still experience the problem with the newly released [v0.6.0](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#060---apr-6-2022)
