### ISSUE TITLE
Plans for using VSCode native testing UI?

### ISSUE THREAD

**Issue by minoseah629** [lucono/karma-test-explorer#31]
Test Explorer UI is in a deprecated state with VS Code having native testing UI built in. 

Is there any plans to move to the native testing? 

https://code.visualstudio.com/api/extension-guides/testing

**Comment by lucono** [comment]
Migrating to the native VS Code test API is the top item in the [recommended areas of focus](https://github.com/lucono/karma-test-explorer/blob/master/CONTRIBUTING.md#recommended-areas-of-focus) for contributing to Karma Test Explorer. I have it on the peripheral radar, but very open to anyone willing to take up the effort of migrating without loss of existing functionality.

**Comment by minoseah629** [comment]
Thank you. 

I just saw the karma test extension was no longer maintained that I had installed but haven't used in a while. https://github.com/Raagh/angular-karma_test-explorer.
