### ISSUE TITLE
Windows file paths cause false-positive duplicate detection

### ISSUE THREAD

**Issue by nwash57** [lucono/karma-test-explorer#4]
SpecLocator gets a mix of Windows and Unix filepaths throughout its lifecycle. When the filepaths are mixed, both styles end up in the cache and then Karma Test Explorer complains that tests/suites have duplicate definitions when in reality they do not. This seems to cause the extension to quit functioning correctly until it is restarted. Disabling watch mode alleviates the breakage, but severely limits the overall functionality/usefulness.

I am not actually positive where the _unix_ filepaths are coming from on my system, as it looks like most things using the public interface of SpecLocator should be using the default Windows paths.

![image](https://user-images.githubusercontent.com/9669523/138322915-4422cb58-f212-45ae-9438-05eaa2248813.png)

Reproduction steps:
1. Open an Angular project in a Windows environment with Karma Test Explorer set up.
2. Let Karma Test Explorer initialize
3. Run tests
4. Edit one of the test files and save it to trigger watch
5. Test Explorer now shows every test as having a duplicate definition

**Comment by lucono** [comment]
@nwash57 I've published [v0.2.1](https://marketplace.visualstudio.com/items?itemName=lucono.karma-test-explorer) to the marketplace with yours and a couple of other fixes (see [changelog](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#021---oct-24-2021)) - thank you! I don't work with Windows very much, so definitely let me know if you run into any other issues on that platform, and you're always welcome to send a pull request!
