### ISSUE TITLE
Can't see or run any tests if one of them has an error in the code.

### ISSUE THREAD

**Issue by edjm1971** [lucono/karma-test-explorer#41]
**Describe the Bug**
I'm newish with VSCode and honestly hate this IDE.
Aside from that I'm new to Angular Testing.
I found your plugin and have spent countless days trying to figure out how to get it to work.
What I had finally discovered was that the projects existing test code that I'm to run has errors in the tests.
If I comment out all of those tests that contain errors, then your extension will load up the working tests and I can run the tests through your extension.

- A clear and concise description of what the bug is.
- see above

**Steps to Reproduce the Behavior**
Create some tests and then create some tests that do not properly create the services that are needed for the components.
I'd give an example but honestly I don't really know how to do these tests yet. I was to use the project as a learning stage but the project is riddled with issues in the code as well as the tests.

**Describe the Expected Behavior**

- A clear and concise description of what you expected to happen.

**Provide Debug Logs**

- With the `karmaTestExplorer.logLevel` set to `debug`, please capture and attach the logs from the `Karma Test Explorer` Output chanel when the issue occurs.
- Please also capture and attach the logs from the `Karma Server` Output channel when the issue occurs.
I do not know what this setting is or where it is that I would set this value?
If you can provide details on this I may be able to update the ticket with this information.

**Screenshots**

- If applicable, add screenshots to help explain the issue you are having.

**Please Provide the Following Information**
 
 - OS: (e.g. macOS)
   -  Linux
 - Environment: (e.g. Dev Container with Guest OS and version)
   - CENTOS8
 - Node Version: (e.g. 14.x)
   - 14.x
 - VS Code Version: 
   - 1.69.1
 - Karma Version:
   - 6.3.16
 - Frameworks: (e.g. Angular, Jasmine, Mocha)
   - Angular, Jasmine

**Additional Context**

- Add any other context about the problem here.

**Comment by edjm1971** [comment]
Only after on a command line running ng test did I see where errors existed in the test files. This extension should identify all *.spec.ts files and also specify if nothing was found in them, tests and pending whereas nothing would be either nothing or errors in those files. Having this extension NOT load at all if some random test buried in the application has an issue is not helpful.

**Comment by lucono** [comment]
The extension itself is not a test framework, and relies on Angular (`ng-test`) for discovering tests in the project. In this case, `ng test` is failing to discover the tests due to the errors in the test files, and so the extension cannot display them either.
