### ISSUE TITLE
If even 1 test fails, tests fail to load Test discovery failed: Process exited with non-zero status code 1 (Click to show log)

### ISSUE THREAD

**Issue by Charuru** [lucono/karma-test-explorer#56]
**Describe the Bug**

Test explorer shows red ! with :Error on the sidebar instead of tests when starting VSCode. Popup says Test discovery failed: Process exited with non-zero status code 1 (Click to show log).

I think I see the tests running on the sidebar normally, after a few seconds all the tests disappear and are replaced with the Error.

**Steps to Reproduce the Behavior**

1. Have a failing test
2. Restart VSCode
3. Check the test explorer sidebar, wait a few seconds
4. red ! with :Error

**Describe the Expected Behavior**

The sidebar to show the tests with green and red tests as normal.

**Provide Debug Logs**

[logs](https://gist.github.com/Charuru/972056dae41100d3ff60e5112c6f7327)

**Screenshots**

**Please Provide the Following Information**
 
 - OS: OSX
 - Environment: (e.g. Dev Container 
with Guest OS and version)
 - Node Version: v16.17.0
 - VS Code Version:  1.72.2
 - Karma Version: 6.4.1
 - Frameworks: Jasmine

**Comment by Charuru** [comment]
This bug seems to be new in 0.7, downgraded to 0.6.1 works fine.

**Comment by Charuru** [comment]
Actually do not need to go back so far, 0.7.3 works correctly.

**Comment by lucono** [comment]
@Charuru I'm not able to reproduce this issue with the latest version, 0.7.5. Can you create and share a minimal project repo that reproduces the issue?

**Comment by Charuru** [comment]
Failure is on startup of vscode.

[Archive.zip](https://github.com/lucono/karma-test-explorer/files/9860818/Archive.zip)

**Comment by lucono** [comment]
Thanks @Charuru. I was able to reproduce the issue consistently with your sample project and when using the jsdom browser, and across all recent versions of the extension, including v0.7.3. I am not however, able to reproduce it with the extension default chrome browser for any of the recent extension versions, including the latest version and v0.7.3.

The issue seems to be with jsdom, where it fails when karma tries to trigger the initial test discovery `/run` request to fully populate the project tests into the test explorer view.

Are you able to reproduce the issue with Chrome, Firefox, or any other browser?

**Comment by Charuru** [comment]
@lucono Thanks for trying it, doesn't make a difference on my machine whether I use jsdom or ChromeCanaryHeadless. Same behavior.

**Comment by Charuru** [comment]
Also, if I click on "Retry Test Load" it will keep on erroring, but if I save the test and it autoruns then the explorer will populate correctly.

I don't know if this is useful information, but when I click on the refresh button on test explorer, I see the tests being runned, all the logs, etc are as expected, and the tests show up for a moment before disappearing in place of the error and then `Failed to load tests - Test discovery failed: Process exited with non-zero status code 1`. This is ChromeCanaryHeadless.

**Comment by Charuru** [comment]
Changing to HTTP from CLI fixed this too.

**Comment by lucono** [comment]
I see, thanks for the update. The `karmaTestExplorer.testTriggerMethod` setting is indeed experimental. In fact, its `http` option is stable, but the `cli` trigger method is actually what's experimental, so I'm not surprised that you ran into issues using that option.

Glad you were able to identify the issue.
