### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by irv075** [lucono/karma-test-explorer#69]
I am unable to install the extension either via VS Code, or by downloading the VSIX manually from the marketplace. The error returned is
`CorruptZip: end of central directory record signature not found`

A colleague has tried on a different PC in a different location and has the same same issue

**Comment by lucono** [comment]
I'm not able to reproduce this on either Windows 11 or MacOS Ventura. Can you provide details of your environment, such as Node version, OS and version, whether using WSL/WSL2, etc.

**Comment by irv075** [comment]
Hmm, I was able to install by connecting from home via my corporate VPN. It's strange how other extensions weren't affected in the same way. I'll close this off now. Thanks!
