### ISSUE TITLE
Nx support

### ISSUE THREAD

**Issue by Siltyx** [lucono/karma-test-explorer#79]
**Is Your Feature Request related to a Problem? Please Describe**

Iam trying to use the extension with a project that uses nx to build.
We use angular + karma + jasmine.

With default settings, the server crashes with:
`19 06 2023 14:21:33.457:ERROR [karma-server]: Server start failed on port 9976: Error: The '@angular-devkit/build-angular/plugins/karma' karma plugin is meant to be used from within Angular CLI and will not work correctly outside of it.`

Setting in manually to angular also doesnt work, since there is only an nx.json and the extension falls back to karma.

I use a custom batch file containing only `"C:\Program Files\nodejs\npx.cmd" nx test --karma-config %2`  as "karmaTestExplorer.karmaProcessCommand",
since passing anything but an absolute path without options to this option results in in the command not beeing found.

Iam not really a web developer and would be thankfull for any guidance on this. 
Did i overlook an obvious solution?

**Comment by lucono** [comment]
No you didn't overlook anything. I'm not familiar with Nx, but Karma Test Explorer currently relies on the `angular.json` file to be able to both identify an Angular workspace as well as discover its sub-projects.

If you would like to work on contributing this feature, it could probably be addressed by adding provider implementations that detect and supply full project configuration for different kinds of setups, including the case for Nx.

**Comment by justdanpo** [comment]
@Siltyx :
We also use nx in our project. As a temporary solution we created angular.json beside every project.json. Example:
```json
{
  "$schema": "../../node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "subProjectName": {
      "projectType": "application",
      "root": "",
      "sourceRoot": "src",
      "architect": {
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "karmaConfig": "../../karma-explorer/karma-explorer.config.js",
            "tsConfig": "tsconfig.karma.spec.json",
            "polyfills": ["src/polyfills.ts", "zone.js", "zone.js/testing"],
            "styles": ["src/styles/styles.scss", "../../node_modules/@angular/cdk/overlay-prebuilt.css"],
            "assets": ["src/favicon.ico", "src/assets"],
            "stylePreprocessorOptions": {
              "includePaths": ["src/styles"]
            },
            "include": ["src/**/*.spec.ts"]
          }
        }
      }
    }
  }
}
```

**Comment by Siltyx** [comment]
@lucono Thanks for the reply. Sadly, I do not have the expertise. Maybe if I find the time. I suppose I need to add something like the code in `src/api/frameworks/angular` for nx? 

@justdanpo thank you, I will try that :) My custom cmd file is not really working great.

**Comment by lucono** [comment]
@Siltyx I'm not very familiar with Nx. If you could share a minimal working sample Angular project (having multiple sub-projects) using Nx, I'll take a closer look.

**Comment by lucono** [comment]
Closing as no response. @Siltyx please reopen if still an issue.

**Comment by justdanpo** [comment]
@lucono here is an example project containing two apps. https://github.com/justdanpo/nx-karma-example
Each app has `project.json` file which looks similar to `angular.json` though with some differences.

To run tests from commandline:
```
export CHROME_BIN=pathtochrome
npx nx run-many -t test --verbose
```

**Comment by justdanpo** [comment]
@Siltyx @lucono could you please reopen the issue?

**Comment by lucono** [comment]
Thanks @justdanpo. Without knowing much about Nx, my thinking is that this could probably be supported by parsing the Nx project files that exist in place of the `angular.json` config. Currently, Angular config parsing happens in the [`angular-util.ts`](https://github.com/lucono/karma-test-explorer/blob/6d0c55674bd73d66a6e6976c402d50cd16fbc57f/src/frameworks/angular/angular-util.ts#L9) file, which provides that information to the [`ProjectFactory`](https://github.com/lucono/karma-test-explorer/blob/6d0c55674bd73d66a6e6976c402d50cd16fbc57f/src/project-factory.ts#L31).

I'm open to a PR - see my earlier [comment](https://github.com/lucono/karma-test-explorer/issues/79#issuecomment-1598096100) on possibly using config providers to support both Angular and Nx project configs (and potentially others). Each provider would be capable of discovering a specific type of config and providing that information to the existing `ProjectFactory` implementation.

**Comment by Siltyx** [comment]
Sorry, i forgot about this. I will be able to take a look at the end of August.

**Comment by lucono** [comment]
Closing (see comment [here](https://github.com/lucono/karma-test-explorer/pull/82#issuecomment-1705922064)).
