### ISSUE TITLE
Yarn PNP support

### ISSUE THREAD

**Issue by SatarisGIT** [lucono/karma-test-explorer#85]
Hello!

Is there any possibility to implement yarn with pnp support for this plugin? I don't have a node_modules file; instead, my project contains zipped dependencies using the yarn pnp mechanism. For this configuration, this extension will noot work.

**Comment by lucono** [comment]
With Karma [deprecated](https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes), there won't be any more feature releases to Karma Test Explorer. The focus is now on preserving the stability of the existing / currently released version.
