### ISSUE TITLE
High CPU usage - vscode hangs when the extension is loaded

### ISSUE THREAD

**Issue by digeomel** [lucono/karma-test-explorer#86]
**Describe the Bug**

I have an Angular workspace with some libraries and a main app, each with their own karma configs. Some libraries and the app have tests. Whenever I open the workspace and the extension is loaded, I get 100% CPU usage and I have to kill vscode entirely. Removing the extension solves the issue, but of course I don't see my tests any more in the test explorer.

**Steps to Reproduce the Behavior**

Described above.

**Describe the Expected Behavior**

Umm, not hang vscode.

**Provide Debug Logs**

I wish I could, but since vscode becomes unresponsive there are no visible output channels. Is there a way to write to a log file instead?

**Provide a Minimal Reproduction Project**

That may take a while, if it's even possible, since this is a corporate/intranet project.

**Screenshots**

Not applicable.

**Please Provide the Following Information**
 
 - OS and Version: Ubuntu 22.04.3 LTS
 - Environment: native
 - Node Version: 18.16.1
 - VS Code Version: 1.82.2
 - Karma Version: 6.4.1
 - Browser and Version: Google Chrome 117.0.5938.62 (Official Build) (64-bit)
 - Frameworks: Angular, Jasmine
 - Angular Version (if using Angular): 15.2.2

**Additional Context**

I understand there's not much to work with here, but I would appreciate any pointers on what to check/change, or a way to write the debug log to a file instead of vscode output watchers. Since nobody else has reported anything like this, I suppose it might be a configuration issue, but I'm not sure what to change/test.

This is a sample `karma.conf.js` file from one of the libraries:

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      jasmine: {
        // you can add configuration options for Jasmine here
        // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
        // for example, you can disable the random execution with `random: false`
        // or set a specific seed with `seed: 4321`
      },
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    jasmineHtmlReporter: {
      suppressAll: true // removes the duplicated traces
    },
    coverageReporter: {
      dir: require('path').join(__dirname, '../../coverage/header-nav'),
      subdir: '.',
      reporters: [
        { type: 'html' },
        { type: 'text-summary' }
      ]
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true
  });
};

```

**Comment by lucono** [comment]
The extension spawns a karma process for _each_ project in your angular workspace, so depending on how many projects you've got in your workspace, it can be expected that attempting to load and work with them all at once will put the pressure of that many karma processes on your CPU, depending also of course on its processing power.

I would check the running processes when this happens to see if it contains anything unexpected, other than the expected number of processes for karma and the associated headless browser processes in line with the number of open angular projects you've got.
