### ISSUE TITLE
Karma server fails to launch when user profile has space in name (Windows)

### ISSUE THREAD

**Issue by peitschie** [lucono/karma-test-explorer#9]
**Describe the Bug**

The Karma Test Explorer extension reports an error starting the Karma Server. This prevents any tests from displaying in VScode.

**Steps to Reproduce the Behavior**

1. Install the Karma Test Explorer extension
2. Open a project (e.g., I used https://github.com/dmitriz/min-karma) in VSCode
3. See error

**Describe the Expected Behavior**

- Ideally the karma server launches and runs 😁 

**Debug Logs**

[karma-server.log](https://github.com/lucono/karma-test-explorer/files/7445392/karma-server.log)
[karma-test-explorer.log](https://github.com/lucono/karma-test-explorer/files/7445393/karma-test-explorer.log)

**Please Provide the Following Information**
 
 - OS: Windows 10
 - Environment: Windows, node 14.16.0, karma 5.0.0, jasmine 3.5.0
 - Version v0.2.1

**Comment by lucono** [comment]
This is fixed in [v0.3.0](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#030---nov-6-2021).

FYI @air2 - for similar issue #2.

**Comment by air2** [comment]
Hey sorry for my late reply, I was on holiday and after that on an other project. Looked at it last week and it was indeed not working, but had no time to figure out why. No I can confirm it works like  a charm. Thank u!!
