### ISSUE TITLE
Angular debug tests only works first time then breakpoint ignored and then Another test operation is still running error occurs

### ISSUE THREAD

**Issue by slagbat** [lucono/karma-test-explorer#90]
I have a problem whereby after debugging a test once the breakpoints stop working for the next run and then the subsequent test run fails because. 

I have to restart VS code to be able to debug again.

I have 'Test Explorer: Use Native Testing' enabled (but the issue happens without native testing too) and its set to use https and not the cli.

**Steps to Reproduce the Behavior**

1. Open VS Code and wait for tests to load
2. Add a breakpoint on a single test and debug it (works fine)
3. Once the test is complete try to debug the test again
4. Test completes but breakpoint is ignored (even though it is shown as attached)
5. Try to debug the test again
6. "New test debug request ignored - Another test operation is still running" error occurs

**Describe the Expected Behavior**

- I can repeatedly debug tests without restarting VS code.

I have attached my logs from Test Explorer and Server

**Please Provide the Following Information**
 
 - OS and Version: Windows 11
 - Environment: WSL2 (Ubuntu)
 - Node Version: v18.15.0
 - VS Code Version: 1.84.2
 - Karma Version: 6.4.0
 - Browser and Version: Chrome headless
 - Frameworks: Jasmine
 - Angular Version (if using Angular): Angular 15

This has always been a bit of an intermittent problem in the past but it is a lot worse now and can be reproduced every time with the steps above.

[karma log.txt](https://github.com/lucono/karma-test-explorer/files/13373062/karma.log.txt)
[karma server log.txt](https://github.com/lucono/karma-test-explorer/files/13373064/karma.server.log.txt)

I suspect the issue is related to my config but any help would be greatly appreciated!

**Comment by lucono** [comment]
@slagbat Note that with the deprecation of Karma runner, this extension is also now [deprecated](https://github.com/lucono/karma-test-explorer/blob/master/README.md#deprecation-notice). While you continue to use Karma and this extension, I encourage you to post any new issues in the [Discussions](https://github.com/lucono/karma-test-explorer/discussions) area to possibly get help from other users.

Having said that, I see this is on WSL, and seems very related to issue #88. Perhaps take a look at the discussion in that issue in case you find it helpful in resolving this issue. If not, post in the Discussions area in case other users are able to help.
